#!/bin/bash
FILE=$1

if [ ! -f Main.class ];
then
  echo "Compiling..."
  make >/dev/null
fi

echo "A Compilação só foi implementada nalguns nós básicos"

filename=$(basename "$FILE")
filename="${filename%.*}"

make c input=$FILE output=$filename > /dev/null

echo "run with: java $filename"
